# fly.toml app configuration file generated for backend-nest on 2025-02-05T14:53:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-nest"
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  port = 8080
  handlers = ["http"]
  force_https = true

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
